"""Initail migration

Revision ID: 5837ec7e6cbb
Revises: 
Create Date: 2026-05-01 15:27:51.063403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5837ec7e6cbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('resources', sa.Enum('user', 'sudoku', name='resourcesenum'), nullable=False),
    sa.Column('action', sa.Enum('create', 'read', 'update', 'delete', name='actionenum'), nullable=False),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('resources', 'action', name='uq_resource_action')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('guest', 'user', 'admin', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sudoku',
    sa.Column('sudoku_id', sa.Integer(), nullable=False),
    sa.Column('sudoku', sa.String(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sudoku_id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solution',
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('solution', sa.String(), nullable=False),
    sa.Column('sudoku_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sudoku_id'], ['sudoku.sudoku_id'], ),
    sa.PrimaryKeyConstraint('solution_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('session_user',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_uuid', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('session_uuid')
    )
    op.create_table('sudoku_solved_user',
    sa.Column('user_solution_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sudoku_id', sa.Integer(), nullable=False),
    sa.Column('solution_user', sa.String(), nullable=False),
    sa.Column('solving_time', sa.Integer(), nullable=False),
    sa.Column('is_solved', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_solution_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sudoku_solved_user')
    op.drop_table('session_user')
    op.drop_table('users')
    op.drop_table('solution')
    op.drop_table('role_permissions')
    op.drop_table('sudoku')
    op.drop_table('role')
    op.drop_table('permissions')
    # ### end Alembic commands ###
